/// This is the back-end's API.
/// This file was generated by kickzig when you created the framework.
/// This file will be never be touched by kickzig.
/// You are free to edit this file.
const std = @import("std");

const _channel_ = @import("channel");
const _startup_ = @import("startup");

const Messenger = @import("messenger/api.zig").Messenger;

var messenger: ?*Messenger = null;
var triggers: *_channel_.Trigger = undefined;

/// KICKZIG TODO:
/// kickStart the backend.
/// Trigger messengers to send their startup messages to the front-end.
pub fn kickStart() !void {}

pub fn init(startup: _startup_.Backend) !void {
    messenger = try Messenger.init(startup);
    triggers = startup.triggers;
}

pub fn deinit() void {
    if (messenger) |member| {
        member.deinit();
    }
}
